config/routes.rb
Rails.application.routes.draw do
  get 'pages/home', to: 'pages#home'
  get 'pages/projects', to: 'pages#projects'
  get 'pages/contact', to: 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
   
  end

  def projects
    
  end

  def contact
     
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiPortafolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary  " data-bs-theme="dark">
      
  <div class="container-fluid">
    <%= link_to 'Mi Portafolio', '/' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Inicio', '/', class: "nav-link #{'active' if current_page?(root_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Proyectos', '/pages/projects', class: "nav-link #{'active' if current_page?(pages_projects_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contacto', '/pages/contact', class: "nav-link #{'active' if current_page?(pages_contact_path)}" %>
        </li>

      </ul>
    </div>
  </div>
 
</nav>
 </div>

<div class="container">
    <%= yield %>
</div>
     <footer class="text-light">
      <div class="container">
        <p>Dayanna Flores 2024. Todos los derechos reservados</p>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<section id="contacto" >
      <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
      
        <h2 class="fw-bold mt-2">Contáctame</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo facilis magnam corrupti ducimus dicta obcaecati? Quae nemo neque incidunt atque, veritatis adipisci minus ea delectus asperiores voluptatum enim nostrum iusto!</p>
        
        <div class="mb-3 ">
            <label for="exampleFormControlInput1" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nombre">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput2" class="form-label">Correo Electrónico</label>
            <input type="email" class="form-control" id="exampleFormControlInput2" placeholder="Correo Electrónico">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Mensaje</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Escribe aquí tu mensaje" rows="3" ></textarea>
          </div>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button class="btn btn-primary me-md-2" type="button">Enviar</button>
            
          </div>
        </div>
      </div>
    </div>
     
    </section>

app/views/pages/home.html.erb
<header>
    <div class="card mb-3" style="max-width: 100%;">
        <div class="row g-0">
            <div class="col-md-4">
                 <%= image_tag 'inicio.jpg', class: 'img-fluid w-100' %>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Dayanna Flores Ferrada</h5>
                    <p class="card-text">Estudiante del bootcamp "Desarrollo Ruby on Rails para emprendimientos de tipo Startup" </p>
                    <p class="card-text"><small class="text-muted">Actualización: 17 de agosto 2024 </small></p>
                </div>
            </div>
        </div>
    </div>
</header>
<section id="misproyectos">
    <div class="container">
        <h2 class="fw-bold mt-2">Mis Proyectos</h2>
       <div class="container text-center">
            <div class="row">
                <div class="col">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag 'proyecto1.jpg' %>
                        <div class="card-body">
                            <h5 class="card-title">Olivia Ros</h5>
                            <p class="card-text">Proyecto creado con Bootstrap, diseñado desde una maqueta</p>
                            <a href="https://dayanaff7.github.io/proyecto_en_bootstrap_olivia/" class="btn btn-primary" target="_blank">Ver mas</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag 'proyecto2.jpg' %>
                        <div class="card-body">
                            <h5 class="card-title">Cuppon</h5>
                            <p class="card-text">Proyecto realizado en bootstrap, desde una maqueta minimizada</p>
                            <a href="https://dayanaff7.github.io/proyecto_en_bootstrap_cuppon/" class="btn btn-primary" target="_blank">Ver mas</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card" style="width: 18rem;">
                     <%= image_tag 'proyecto3.jpg' %>
                        <div class="card-body">
                            <h5 class="card-title">Chile Viajes</h5>
                            <p class="card-text">Proyecto final del módulo 2 creado con bootstrap, css y js. </p>
                            <a href="https://dayanaff7.github.io/ror_examen_m02/" class="btn btn-primary" target="_blank">Ver mas</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>        
</section>
<section id="contacto" >
      <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
      
        <h2 class="fw-bold mt-2">Contáctame</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo facilis magnam corrupti ducimus dicta obcaecati? Quae nemo neque incidunt atque, veritatis adipisci minus ea delectus asperiores voluptatum enim nostrum iusto!</p>
        
        <div class="mb-3 ">
            <label for="exampleFormControlInput1" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nombre">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput2" class="form-label">Correo Electrónico</label>
            <input type="email" class="form-control" id="exampleFormControlInput2" placeholder="Correo Electrónico">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Mensaje</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Escribe aquí tu mensaje" rows="3" ></textarea>
          </div>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button class="btn btn-primary me-md-2" type="button">Enviar</button>
            
          </div>
        </div>
      </div>
    </div>
     
    </section>

app/views/pages/projects.html.erb
<section id="misproyectos">
    <div class="container">
        <h2 class="fw-bold mt-2">Mis Proyectos</h2>
       <div class="container text-center">
            <div class="row">
                <div class="col">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag 'proyecto1.jpg' %>
                        <div class="card-body">
                            <h5 class="card-title">Olivia Ros</h5>
                            <p class="card-text">Proyecto creado con Bootstrap, diseñado desde una maqueta</p>
                            <a href="https://dayanaff7.github.io/proyecto_en_bootstrap_olivia/" class="btn btn-primary" target="_blank">Ver mas</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag 'proyecto2.jpg' %>
                        <div class="card-body">
                            <h5 class="card-title">Cuppon</h5>
                            <p class="card-text">Proyecto realizado en bootstrap, desde una maqueta minimizada</p>
                            <a href="https://dayanaff7.github.io/proyecto_en_bootstrap_cuppon/" class="btn btn-primary" target="_blank">Ver mas</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card" style="width: 18rem;">
                     <%= image_tag 'proyecto3.jpg' %>
                        <div class="card-body">
                            <h5 class="card-title">Chile Viajes</h5>
                            <p class="card-text">Proyecto final del módulo 2 creado con bootstrap, css y js. </p>
                            <a href="https://dayanaff7.github.io/ror_examen_m02/" class="btn btn-primary" target="_blank">Ver mas</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>        
</section>